#!/bin/bash

################
# Setting for easier shell usage
################
# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# search within installed debian packages
alias lspack="dpkg -l | grep ^ii | awk '{print \$2}' | grep"

# set up aliases for python and python3 in order to add specific library paths
alias python="PYTHONPATH=${PYTHON2PATH:+$PYTHON2PATH:}$PYTHONPATH python"
alias python3="PYTHONPATH=${PYTHON3PATH:+$PYTHON3PATH:}$PYTHONPATH python3"

################
# Alias for remote setting to rpuck02
################
# rpuck02 is currently on the Turtlebot 2 platform
# this alias requires rpuck02 are registered hostnames on the network

# ssh connection to TX2 rpuck02
alias ssh2rp2="ssh2rpuck rpuck02"

# set the local system listen to remote ROS master node on rpuck02
alias ros2rp2="ros2rpuck rpuck02"

###### setup gpip for global 'pip' command
alias gpip="PIP_REQUIRE_VIRTUALENV=\"\" pip"

