#!/bin/bash

# set vim as default editor
export EDITOR="vim"

# setup Eigen3 path
# need to check if Eigen3 is installed
# export Eigen3_INCLUDE_DIRS=/usr/local/include/eigen3

###### export virtualenvwrapper's WORKON_HOME
export WORKON_HOME=~/Workspace/PyEnvs


###### disable 'pip' command
export PIP_REQUIRE_VIRTUALENV=true


###### export the Cuda and Nsight path to PATH env
export PATH=/usr/local/cuda/bin:/usr/local/cuda/NsightCompute-2019.3${PATH:+:${PATH}}

