#!/bin/bash

################
# source customisation files into shell
################

# # to set up the local catkin workspace path
# source ~/catkin_ws/devel/setup.bash

###### export virtualenvwrapper's WORKON_HOME
source ~/.local/bin/virtualenvwrapper.sh


###### export ROS Kinetic environment variables
source /opt/ros/kinetic/setup.bash

